package static

const (
	ARROW_NOT_FOUND                                   = "ARROW_NOT_FOUND"
	FAILED_TO_CHECK_AGGREGATE_EXISTENCE               = "FAILED_TO_CHECK_AGGREGATE_EXISTENCE"
	FAILED_TO_CHECK_SUCCEEDED_EVENT                   = "FAILED_TO_CHECK_SUCCEEDED_EVENT"
	FAILED_TO_GET_EVENT_STREAM                        = "FAILED_TO_GET_EVENT_STREAM"
	ARROW_ALREADY_EXISTS                              = "ARROW_ALREADY_EXISTS"
	AGGREGATE_DOES_NOT_EXIST                          = "AGGREGATE_DOES_NOT_EXIST"
	AGGREGATE_DOES_NOT_HAVE_SUCCEEDED_ADD_ARROW_EVENT = "AGGREGATE_DOES_NOT_HAVE_SUCCEEDED_ADD_ARROW_EVENT"
	AGGREGATE_HAS_ACTIVE_EXECUTION                    = "AGGREGATE_HAS_ACTIVE_EXECUTION"
	FAILED_TO_CHECK_STARTED_EVENT                     = "FAILED_TO_CHECK_STARTED_EVENT"
)
