package errors

type ErrorCode int

const (
	// ? 2xx Success
	SuccessCode                     ErrorCode = 200 // 200 - Success (Won't retry)
	CreatedCode                     ErrorCode = 201 // 201 - Created (Won't retry)
	AcceptedCode                    ErrorCode = 202 // 202 - Accepted (Won't retry)
	NonAuthoritativeInformationCode ErrorCode = 203 // 203 - Non-Authoritative Information (Won't retry)
	NoContentCode                   ErrorCode = 204 // 204 - No Content (Won't retry)
	ResetContentCode                ErrorCode = 205 // 205 - Reset Content (Won't retry)
	PartialContentCode              ErrorCode = 206 // 206 - Partial Content (Won't retry)
	MultiStatusCode                 ErrorCode = 207 // 207 - Multi-Status (Won't retry)
	AlreadyReportedCode             ErrorCode = 208 // 208 - Already Reported (Won't retry)
	IMUsedCode                      ErrorCode = 226 // 226 - IM Used (Won't retry)

	// ? 4xx Client Error
	InvalidRequestCode              ErrorCode = 400 // 400 - Bad Request (Won't retry)
	UnauthorizedCode                ErrorCode = 401 // 401 - Unauthorized (Won't retry)
	PaymentRequiredCode             ErrorCode = 402 // 402 - Payment Required (Won't retry)
	ForbiddenCode                   ErrorCode = 403 // 403 - Forbidden (Won't retry)
	NotFoundCode                    ErrorCode = 404 // 404 - Not Found (Won't retry)
	MethodNotAllowedCode            ErrorCode = 405 // 405 - Method Not Allowed (Won't retry)
	NotAcceptableCode               ErrorCode = 406 // 406 - Not Acceptable (Won't retry)
	ProxyAuthenticationRequiredCode ErrorCode = 407 // 407 - Proxy Authentication Required (Won't retry)
	RequestTimeoutCode              ErrorCode = 408 // 408 - Request Timeout (Won't retry)
	ConflictCode                    ErrorCode = 409 // 409 - Conflict (Won't retry)
	GoneCode                        ErrorCode = 410 // 410 - Gone (Won't retry)
	LengthRequiredCode              ErrorCode = 411 // 411 - Length Required (Won't retry)
	PreconditionFailedCode          ErrorCode = 412 // 412 - Precondition Failed (Won't retry)
	PayloadTooLargeCode             ErrorCode = 413 // 413 - Payload Too Large (Won't retry)
	URITooLongCode                  ErrorCode = 414 // 414 - URI Too Long (Won't retry)
	UnsupportedMediaTypeCode        ErrorCode = 415 // 415 - Unsupported Media Type (Won't retry)
	RangeNotSatisfiableCode         ErrorCode = 416 // 416 - Range Not Satisfiable (Won't retry)
	ExpectationFailedCode           ErrorCode = 417 // 417 - Expectation Failed (Won't retry)
	ImATeapotCode                   ErrorCode = 418 // 418 - I'm a teapot (Won't retry)
	MisdirectedRequestCode          ErrorCode = 421 // 421 - Misdirected Request (Won't retry)
	UnprocessableEntityCode         ErrorCode = 422 // 422 - Unprocessable Entity (Won't retry)
	LockedCode                      ErrorCode = 423 // 423 - Locked (Won't retry)
	FailedDependencyCode            ErrorCode = 424 // 424 - Failed Dependency (Won't retry)
	TooEarlyCode                    ErrorCode = 425 // 425 - Too Early (Won't retry)
	UpgradeRequiredCode             ErrorCode = 426 // 426 - Upgrade Required (Won't retry)
	PreconditionRequiredCode        ErrorCode = 428 // 428 - Precondition Required (Won't retry)
	TooManyRequestsCode             ErrorCode = 429 // 429 - Too Many Requests (Won't retry)
	RequestHeaderFieldsTooLargeCode ErrorCode = 431 // 431 - Request Header Fields Too Large (Won't retry)
	UnavailableForLegalReasonsCode  ErrorCode = 451 // 451 - Unavailable For Legal Reasons (Won't retry)

	// ? 5xx Server Error
	InternalServerCode                ErrorCode = 500 // 500 - Internal Server Error (Will retry)
	NotImplementedCode                ErrorCode = 501 // 501 - Not Implemented (Will retry)
	BadGatewayCode                    ErrorCode = 502 // 502 - Bad Gateway (Will retry)
	ServiceUnavailableCode            ErrorCode = 503 // 503 - Service Unavailable (Will retry)
	GatewayTimeoutCode                ErrorCode = 504 // 504 - Gateway Timeout (Will retry)
	HTTPVersionErrorCode              ErrorCode = 505 // 505 - HTTP Version Not Supported (Will retry)
	VariantAlsoNegotiatesCode         ErrorCode = 506 // 506 - Variant Also Negotiates (Will retry)
	InsufficientStorageCode           ErrorCode = 507 // 507 - Insufficient Storage (Will retry)
	LoopDetectedCode                  ErrorCode = 508 // 508 - Loop Detected (Will retry)
	NotExtendedCode                   ErrorCode = 510 // 510 - Not Extended (Will retry)
	NetworkAuthenticationRequiredCode ErrorCode = 511 // 511 - Network Authentication Required (Will retry)
)
