// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/arrow": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1 / Arrows"
                ],
                "summary": "List arrows",
                "responses": {
                    "200": {
                        "description": "Success without warnings",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.SuccessResponseDocsDTO-map_string_github_com_rabbytesoftware_quiver_internal_models_arrow_Arrow"
                        }
                    },
                    "206": {
                        "description": "Success with warnings",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.WarningResponseDocsDTO-map_string_github_com_rabbytesoftware_quiver_internal_models_arrow_Arrow"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.ErrorResponseDocsDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/arrow/{namespace}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1 / Arrows"
                ],
                "summary": "Get arrow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Arrow namespace (namespace | url | directory)",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success without warnings",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.SuccessResponseDocsDTO-github_com_rabbytesoftware_quiver_internal_models_arrow_Arrow"
                        }
                    },
                    "206": {
                        "description": "Success with warnings",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.WarningResponseDocsDTO-github_com_rabbytesoftware_quiver_internal_models_arrow_Arrow"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.ErrorResponseDocsDTO"
                        }
                    },
                    "404": {
                        "description": "Arrow not found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.ErrorResponseDocsDTO"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1 / Arrows"
                ],
                "summary": "Add an arrow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Arrow namespace (namespace | url | directory)",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success without warnings",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.SuccessResponseDocsDTO-github_com_rabbytesoftware_quiver_internal_models_arrow_Arrow"
                        }
                    },
                    "206": {
                        "description": "Success with warnings",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.WarningResponseDocsDTO-github_com_rabbytesoftware_quiver_internal_models_arrow_Arrow"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.ErrorResponseDocsDTO"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1 / Arrows"
                ],
                "summary": "Remove an arrow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Arrow namespace (namespace | url | directory)",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success without warnings",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.SuccessResponseWithoutPayloadDocsDTO"
                        }
                    },
                    "206": {
                        "description": "Success with warnings",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.WarningResponseWithoutPayloadDocsDTO"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.ErrorResponseDocsDTO"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.ErrorResponseDocsDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/arrow/{namespace}/kill/{method}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1 / Arrows"
                ],
                "summary": "Kill method",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Arrow namespace (namespace | url | directory)",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Method name",
                        "name": "method",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success without warnings",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.SuccessResponseWithoutPayloadDocsDTO"
                        }
                    },
                    "206": {
                        "description": "Success with warnings",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.WarningResponseWithoutPayloadDocsDTO"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.ErrorResponseDocsDTO"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.ErrorResponseDocsDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/arrow/{namespace}/stop/{method}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1 / Arrows"
                ],
                "summary": "Stop method",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Arrow namespace (namespace | url | directory)",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Method name",
                        "name": "method",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success without warnings",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.SuccessResponseWithoutPayloadDocsDTO"
                        }
                    },
                    "206": {
                        "description": "Success with warnings",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.WarningResponseWithoutPayloadDocsDTO"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.ErrorResponseDocsDTO"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.ErrorResponseDocsDTO"
                        }
                    }
                }
            }
        },
        "/api/v1/arrow/{namespace}/{method}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1 / Arrows"
                ],
                "summary": "Execute arrow method",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Arrow namespace (namespace | url | directory)",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Method name",
                        "name": "method",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Execute method variables",
                        "name": "variables",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.ExecuteMethodRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Success without warnings",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.SuccessResponseWithoutPayloadDocsDTO"
                        }
                    },
                    "206": {
                        "description": "Success with warnings",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.WarningResponseWithoutPayloadDocsDTO"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.ErrorResponseDocsDTO"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_v1_handlers_arrows.ErrorResponseDocsDTO"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_rabbytesoftware_quiver_internal_models_arrow.Action": {
            "type": "object",
            "properties": {
                "exit_on_failure": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "timeout": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/github_com_rabbytesoftware_quiver_internal_models_arrow.ActionType"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "github_com_rabbytesoftware_quiver_internal_models_arrow.ActionType": {
            "type": "string",
            "enum": [
                "run",
                "download",
                "copy",
                "uncompress"
            ],
            "x-enum-varnames": [
                "ActionTypeRun",
                "ActionTypeDownload",
                "ActionTypeCopy",
                "ActionTypeUncompress"
            ]
        },
        "github_com_rabbytesoftware_quiver_internal_models_arrow.Arrow": {
            "type": "object",
            "properties": {
                "arrow_version": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "banner_url": {
                    "type": "string"
                },
                "credits": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dependencies": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "documentation": {
                    "type": "string"
                },
                "icon_url": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "license": {
                    "type": "string"
                },
                "maintainers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "methods": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_rabbytesoftware_quiver_internal_models_arrow.Method"
                    }
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "netbridge": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_rabbytesoftware_quiver_internal_models_netbridge.PortRule"
                    }
                },
                "quiver_url": {
                    "type": "string"
                },
                "requirements": {
                    "$ref": "#/definitions/github_com_rabbytesoftware_quiver_internal_models_arrow.Requirement"
                },
                "url": {
                    "type": "string"
                },
                "variables": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_rabbytesoftware_quiver_internal_models_arrow.Variable"
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "github_com_rabbytesoftware_quiver_internal_models_arrow.Method": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_rabbytesoftware_quiver_internal_models_arrow.Action"
                    }
                },
                "dependencies": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "method_name": {
                    "type": "string"
                },
                "platforms": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "workdir": {
                    "type": "string"
                }
            }
        },
        "github_com_rabbytesoftware_quiver_internal_models_arrow.Requirement": {
            "type": "object",
            "properties": {
                "cpu_cores": {
                    "type": "integer"
                },
                "disk": {
                    "type": "integer"
                },
                "memory": {
                    "type": "integer"
                },
                "network_mbps": {
                    "type": "integer"
                },
                "os": {
                    "$ref": "#/definitions/github_com_rabbytesoftware_quiver_internal_models_shared.OS"
                }
            }
        },
        "github_com_rabbytesoftware_quiver_internal_models_arrow.Variable": {
            "type": "object",
            "properties": {
                "default": {
                    "type": "string"
                },
                "max": {
                    "type": "integer"
                },
                "min": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "sensitive": {
                    "type": "boolean"
                },
                "type": {
                    "$ref": "#/definitions/github_com_rabbytesoftware_quiver_internal_models_arrow.VariableType"
                },
                "values": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_rabbytesoftware_quiver_internal_models_arrow.VariableType": {
            "type": "string",
            "enum": [
                "string",
                "number",
                "boolean"
            ],
            "x-enum-varnames": [
                "VariableTypeString",
                "VariableTypeNumber",
                "VariableTypeBoolean"
            ]
        },
        "github_com_rabbytesoftware_quiver_internal_models_netbridge.ForwardingStatus": {
            "type": "string",
            "enum": [
                "enabled",
                "disabled",
                "error"
            ],
            "x-enum-varnames": [
                "ForwardingStatusEnabled",
                "ForwardingStatusDisabled",
                "ForwardingStatusError"
            ]
        },
        "github_com_rabbytesoftware_quiver_internal_models_netbridge.PortRule": {
            "type": "object",
            "properties": {
                "end_port": {
                    "type": "integer"
                },
                "forwarding_status": {
                    "$ref": "#/definitions/github_com_rabbytesoftware_quiver_internal_models_netbridge.ForwardingStatus"
                },
                "id": {
                    "type": "string"
                },
                "protocol": {
                    "$ref": "#/definitions/github_com_rabbytesoftware_quiver_internal_models_netbridge.Protocol"
                },
                "start_port": {
                    "type": "integer"
                }
            }
        },
        "github_com_rabbytesoftware_quiver_internal_models_netbridge.Protocol": {
            "type": "string",
            "enum": [
                "tcp",
                "udp",
                "tcp/udp"
            ],
            "x-enum-varnames": [
                "ProtocolTCP",
                "ProtocolUDP",
                "ProtocolTCPUDP"
            ]
        },
        "github_com_rabbytesoftware_quiver_internal_models_shared.OS": {
            "type": "string",
            "enum": [
                "linux/amd64",
                "linux/arm64",
                "windows/amd64",
                "windows/arm64",
                "darwin/amd64",
                "darwin/arm64"
            ],
            "x-enum-varnames": [
                "OSLinuxAMD64",
                "OSLinuxARM64",
                "OSWindowsAMD64",
                "OSWindowsARM64",
                "OSDarwinAMD64",
                "OSDarwinARM64"
            ]
        },
        "internal_api_v1_handlers_arrows.ErrorResponseDocsDTO": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/internal_api_v1_handlers_arrows.responseError"
                },
                "responseTime": {
                    "type": "string",
                    "example": "150ms"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-05T15:04:05Z"
                }
            }
        },
        "internal_api_v1_handlers_arrows.ExecuteMethodRequestDTO": {
            "type": "object",
            "properties": {
                "variables": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_api_v1_handlers_arrows.SuccessResponseDocsDTO-github_com_rabbytesoftware_quiver_internal_models_arrow_Arrow": {
            "type": "object",
            "properties": {
                "payload": {
                    "$ref": "#/definitions/github_com_rabbytesoftware_quiver_internal_models_arrow.Arrow"
                },
                "responseTime": {
                    "type": "string",
                    "example": "300ms"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-05T15:04:05Z"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[]"
                    ]
                }
            }
        },
        "internal_api_v1_handlers_arrows.SuccessResponseDocsDTO-map_string_github_com_rabbytesoftware_quiver_internal_models_arrow_Arrow": {
            "type": "object",
            "properties": {
                "payload": {
                    "$ref": "#/definitions/map_string_github_com_rabbytesoftware_quiver_internal_models_arrow.Arrow"
                },
                "responseTime": {
                    "type": "string",
                    "example": "300ms"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-05T15:04:05Z"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[]"
                    ]
                }
            }
        },
        "internal_api_v1_handlers_arrows.SuccessResponseWithoutPayloadDocsDTO": {
            "type": "object",
            "properties": {
                "responseTime": {
                    "type": "string",
                    "example": "300ms"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-05T15:04:05Z"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[]"
                    ]
                }
            }
        },
        "internal_api_v1_handlers_arrows.WarningResponseDocsDTO-github_com_rabbytesoftware_quiver_internal_models_arrow_Arrow": {
            "type": "object",
            "properties": {
                "payload": {
                    "$ref": "#/definitions/github_com_rabbytesoftware_quiver_internal_models_arrow.Arrow"
                },
                "responseTime": {
                    "type": "string",
                    "example": "215ms"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-05T15:04:05Z"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "minor warning"
                    ]
                }
            }
        },
        "internal_api_v1_handlers_arrows.WarningResponseDocsDTO-map_string_github_com_rabbytesoftware_quiver_internal_models_arrow_Arrow": {
            "type": "object",
            "properties": {
                "payload": {
                    "$ref": "#/definitions/map_string_github_com_rabbytesoftware_quiver_internal_models_arrow.Arrow"
                },
                "responseTime": {
                    "type": "string",
                    "example": "215ms"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-05T15:04:05Z"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "minor warning"
                    ]
                }
            }
        },
        "internal_api_v1_handlers_arrows.WarningResponseWithoutPayloadDocsDTO": {
            "type": "object",
            "properties": {
                "responseTime": {
                    "type": "string",
                    "example": "215ms"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-05T15:04:05Z"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "minor warning"
                    ]
                }
            }
        },
        "internal_api_v1_handlers_arrows.responseError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 500
                },
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "message": {
                    "type": "string",
                    "example": "something went wrong"
                }
            }
        },
        "map_string_github_com_rabbytesoftware_quiver_internal_models_arrow.Arrow": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/github_com_rabbytesoftware_quiver_internal_models_arrow.Arrow"
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
